<?php

	/* ********************************************************
	 * ********************************************************
	 * ********************************************************/
	class MapZsListView extends ProjectAbstractView {

        /* ********************************************************
         * ********************************************************
         * ********************************************************/
        public function displayContent() {
			?>
                <link rel="stylesheet" href="<?php print(RequestHelper::$url_root); ?>/js/Leaflet/leaflet.css" type="text/css" />
                <link rel="stylesheet" href="<?php print(RequestHelper::$url_root); ?>/css/map.css" type="text/css" />
                <script type="text/javascript" src="<?php print(RequestHelper::$url_root); ?>/js/Leaflet/leaflet.js"></script>
                <script type="text/javascript" src="<?php print(RequestHelper::$url_root); ?>/js/Leaflet/leaflet-simple-map-screenshoter.js"></script>
                <script type="text/javascript" src="<?php print(RequestHelper::$url_root); ?>/js/map_zs_list.js"></script>
                
				<!-- <h1>
                    <?php print(RequestHelper::$actor_class_name); ?>
                    <?php print(RequestHelper::$actor_action); ?>
                </h1> -->
                <h1>
                    Zsanett questionnaire participants
                </h1>
                
                <div id="map_full"></div>
                <br clear="all" />

                <script type="text/javascript">
                    // Embed the JSON data generated by PHP directly into a JavaScript variable
                    const mapData = <?php print($this->do->json_data); ?>;

                    // Log the data (optional, but good for debugging)
                    console.log("Data loaded from PHP:", mapData);

                    // Call the map initialization function defined in index.js
                    // NOTE: This requires that you have updated index.js as previously recommended.
                    if (typeof initializeMap === 'function') {
                        initializeMap(mapData);
                    } else {
                        console.error("The initializeMap function is not defined in index.js. Check your script loading order.");
                    }
                </script>

			<?php
		}

    }

?>