<?php

	/* ********************************************************
	 * ********************************************************
	 * ********************************************************/
	class MapV2ListView extends ProjectAbstractView {

        /* ********************************************************
         * ********************************************************
         * ********************************************************/
        public function displayContent() {
			?>
                <link rel="stylesheet" href="<?php print(RequestHelper::$url_root); ?>/js/Leaflet/leaflet.css" type="text/css" />
                <style>
                    #map {
                        height: 60vh;
                        width: 65vw;
                        border: 1px solid #000;
                        margin: auto;
                        margin: 10px;
                        float: left;
                    }
                    #map_log {
                        width: 17vw;
                        float: right;
                        font-size: 10px;
                        margin-left: 0px;
                    }
                    #map_full {
                        height: 80vh;
                        width: 94vw;
                        border: 1px solid #000;
                        margin: auto;
                        margin: 10px;
                        float: left;
                    }
                </style>
                <script type="text/javascript" src="<?php print(RequestHelper::$url_root); ?>/js/Leaflet/leaflet.js"></script>
                <script type="text/javascript" src="<?php print(RequestHelper::$url_root); ?>/js/Leaflet/leaflet-simple-map-screenshoter.js"></script>
                <script type="text/javascript" src="<?php print(RequestHelper::$url_root); ?>/js/map_v2_list.js"></script>
                
				<!-- <h1>
                    <?php print(RequestHelper::$actor_class_name); ?>
                    <?php print(RequestHelper::$actor_action); ?>
                </h1> -->
                <h1>
                    Map of questionnaire responders count by postal codes
                </h1>
                
                <div id="map_full"></div>
                <br clear="all" />

                <script type="text/javascript">
                    // Embed the JSON data generated by PHP directly into a JavaScript variable
                    const mapData = <?php print($this->do->json_data); ?>;

                    // Log the data (optional, but good for debugging)
                    console.log("Data loaded from PHP:", mapData);

                    // Call the map initialization function defined in index.js
                    // NOTE: This requires that you have updated index.js as previously recommended.
                    if (typeof initializeMap === 'function') {
                        initializeMap(mapData);
                    } else {
                        console.error("The initializeMap function is not defined in index.js. Check your script loading order.");
                    }
                </script>

			<?php
		}

    }

?>