CREATE TABLE 02773_research.form_responses_drone_reservists_v1 (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `submitted_at` datetime,
    `age` INT,
    `gender` VARCHAR(50),
    `postal_code` INT,
    `education` VARCHAR(255),
    `years_of_service` INT,
    `rank` VARCHAR(255),
    `drone_familiarity` VARCHAR(255),
    `labor_market_status` VARCHAR(255),
    `income_net` INT,
    `employer_size` VARCHAR(255),
    `employment_ownership` VARCHAR(255),
    `employer_form` VARCHAR(255),
    `S1` INT,
    `S2` INT,
    `S3` INT,
    `S4` INT,
    `W1` INT,
    `W2` INT,
    `W3` INT,
    `W4` INT,
    `O1` INT,
    `O2` INT,
    `O3` INT,
    `O4` INT,
    `T1` INT,
    `T2` INT,
    `T3` INT,
    `T4` INT
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;